### ISSUE TITLE
@import breaks when the path is in double-quotes rather than single-quotes

### ISSUE THREAD

**Issue by jackhorton** [lasso-js/lasso-less#10]
When declaring a file as a dependency in browser.json and @import-ing it, using double-quotes will cause the import to fail and error out, while using single-quotes will work just fine.

Given `browser.json`
```json
{
    "dependencies": [
        "..."
        "path/to/some/module/browser.json",
        "..."
    ]
}
```

This breaks
```less
@import "path/to/some/module/breaks.less";
```

While this works
```less
@import 'path/to/some/module/works.less';
```

**Comment by patrick-steele-idem** [comment]
Double versus single quotes shouldn't matter. Looks like a bug that is likely related to the regular expression that we are using to find the `@import` statements. Let me take a look.
