### ISSUE TITLE
support strictMath config for less

### ISSUE THREAD

**Issue by yomed** [lasso-js/lasso-less#13]
I'd like to enable the --strict-math setting in less. Is there some way to pass in generic config through the pluginConfig object? Or would lasso-less need to explicitly support it like `config.urlResolver`?

**Comment by patrick-steele-idem** [comment]
Hi @yomed, that would be a nice thing to support and it would not be too difficult. How about we add support for a `lessConfig` option that would be an object that we pass directly to `less`? Here's the relevant code:

- Less config built: https://github.com/lasso-js/lasso-less/blob/cbad9344bc3ce0d6f0dc2114888025a322abf57e/lib/dependency-less.js#L121-L124
- The `config` argument is the plugin configuration: https://github.com/lasso-js/lasso-less/blob/cbad9344bc3ce0d6f0dc2114888025a322abf57e/lib/dependency-less.js#L7

I'm thinking the following:

```javascript
var parseConfig = {
    filename: 'lasso.less',
    paths: [process.cwd()]
};
if (config.lessConfig) {
    extend(parseConfig, config.lessConfig);
}
```

If you are able to make and test this change that would be very helpful. Thoughts?

**Comment by yomed** [comment]
Sounds good, will send a PR soon
