### ISSUE TITLE
Order not maintained if CSS and less files are intermingled

### ISSUE THREAD

**Issue by senthilp** [lasso-js/lasso-less#15]
Currently if an application has a CSS file, followed by a less file in `browser.json`, the CSS file is inserted after all the less files included in the stylesheet. This breaks ordering.

**Comment by patrick-steele-idem** [comment]
New version published: `lasso-less@2.2.0`

See updated docs: https://github.com/lasso-js/lasso-less#configuration

Specifically, you will need to set `extensions` to `['less', 'css']` if you want order to be maintained

Please let me know if you see any issues.

**Comment by patrick-steele-idem** [comment]
Things are still broken when bundling is disabled. Reopening the issue.

**Comment by patrick-steele-idem** [comment]
Fixed. New version published: `lasso-less@2.2.1`
